# Generated by Django 2.2.5 on 2019-12-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCommodity',
            fields=[
                ('commodity_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('category_id', models.CharField(blank=True, max_length=20, null=True)),
                ('commodity_category', models.CharField(max_length=20)),
                ('brand_id', models.CharField(blank=True, max_length=20, null=True)),
                ('commodity_brand', models.CharField(max_length=20)),
                ('commodity_doc', models.CharField(blank=True, max_length=200, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_commodity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TLoginUser',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_login_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TMerchant',
            fields=[
                ('merchant_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gmv', models.CharField(blank=True, db_column='GMV', max_length=50, null=True)),
            ],
            options={
                'db_table': 't_merchant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('preference', models.CharField(blank=True, max_length=50, null=True)),
                ('consume_level', models.CharField(blank=True, max_length=20, null=True)),
                ('consume_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('area_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUserAddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('commodity_id', models.CharField(blank=True, max_length=20, null=True)),
                ('time_stamp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_user_add_to_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUserAddToFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('commodity_id', models.CharField(blank=True, max_length=20, null=True)),
                ('time_stamp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_user_add_to_favorite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUserClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('commodity_id', models.CharField(blank=True, max_length=20, null=True)),
                ('time_stamp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_user_click',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUserPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('commodity_id', models.CharField(blank=True, max_length=20, null=True)),
                ('time_stamp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_user_purchase',
                'managed': False,
            },
        ),
    ]
